### ISSUE TITLE
PyPI Conduit Namespace

### ISSUE THREAD

**Issue by bbengfort** [sleibman/python-conduit#1]
Hi @sleibman - I wanted to drop you a note because I'm working on a Python package that applies dataflow computations to time series streams of power engineering data (e.g. voltage and current synchrophasor measurements). The project is called conduit, probably for the same reason you named your project conduit! I've noticed that your project has been inactive since 2013; would you be willing to free up the namespace on PyPI so that we could register our library with the same name? We'd be happy to give you a shout out in our README and point to your original project if you wanted.

**Comment by sleibman** [comment]
Hi @bbengfort ,
Sure, you can have conduit.
I looked at how to transfer pypi names, and the suggestion is to add a new owner and let the new owner overwrite the project. It also looks like I could delete the project, but I don't know if it will hold onto the name for a while or anything like that.

So... I will add you as an owner, and you can take whatever approach you want (including removing me as an owner or deleting the pypi project if that looks like the right thing to do).

To do so, I need your pypi username.
You can put it here, or email to sleibman@gmail.com
